# We tried to automate pushing the build to a branch using Travis
# But we didn't want to give Travis access to all our Github repos
language: node_js
node_js:
  - "node"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install

cache:
  directories:
    - "node_modules"

script: npm build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: build-test
  on:
    branch: release
